services:
  ollama:
    image: ollama/ollama:0.1.25
    container_name: ollama_service
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    # Se você tiver uma GPU NVIDIA e o toolkit docker configurado,
    # descomente as linhas abaixo para aceleração de hardware:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

volumes:
  ollama_data:
